// Generated by generate-schema.ts from `herdr api schema --json`. Do not edit.
import { Schema } from "effect"

const HerdrErrorBodySchema = Schema.Struct({
  code: Schema.String,
  message: Schema.String
})

export const HerdrErrorResponseSchema = Schema.Struct({
  error: HerdrErrorBodySchema,
  id: Schema.String
})
export const decodeHerdrErrorResponse = Schema.decodeUnknownOption(HerdrErrorResponseSchema)

const HerdrAgentSessionRefKindSchema = Schema.Literals(["id", "path"])

const HerdrAgentSessionInfoSchema = Schema.Struct({
  agent: Schema.String,
  kind: HerdrAgentSessionRefKindSchema,
  source: Schema.String,
  value: Schema.String
})

const HerdrAgentStatusSchema = Schema.Literals(["idle", "working", "blocked", "done", "unknown"])

const HerdrAgentInfoSchema = Schema.Struct({
  agent: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  agent_session: Schema.optionalKey(Schema.Union([HerdrAgentSessionInfoSchema, Schema.Null])),
  agent_status: HerdrAgentStatusSchema,
  cwd: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  display_agent: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  focused: Schema.Boolean,
  foreground_cwd: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  interactive_ready: Schema.optionalKey(Schema.Boolean),
  launch_pending: Schema.optionalKey(Schema.Boolean),
  name: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  pane_id: Schema.String,
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  screen_detection_skipped: Schema.optionalKey(Schema.Boolean),
  state_change_seq: Schema.optionalKey(Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))),
  state_labels: Schema.optionalKey(Schema.Record(Schema.String, Schema.String)),
  tab_id: Schema.String,
  terminal_id: Schema.String,
  terminal_title: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  terminal_title_stripped: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  title: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  tokens: Schema.optionalKey(
    Schema.Record(
      Schema.String.check(Schema.isPattern(new RegExp("^[A-Za-z0-9_-]{1,32}$"))),
      Schema.String
    ).check(Schema.isMaxProperties(32))
  ),
  workspace_id: Schema.String
})

const HerdrPaneScrollInfoSchema = Schema.Struct({
  max_offset_from_bottom: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  offset_from_bottom: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  viewport_rows: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))
})

const HerdrPaneInfoSchema = Schema.Struct({
  agent: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  agent_session: Schema.optionalKey(Schema.Union([HerdrAgentSessionInfoSchema, Schema.Null])),
  agent_status: HerdrAgentStatusSchema,
  cwd: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  display_agent: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  focused: Schema.Boolean,
  foreground_cwd: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  label: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  pane_id: Schema.String,
  revision: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  scroll: Schema.optionalKey(Schema.Union([HerdrPaneScrollInfoSchema, Schema.Null])),
  state_labels: Schema.optionalKey(Schema.Record(Schema.String, Schema.String)),
  tab_id: Schema.String,
  terminal_id: Schema.String,
  terminal_title: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  terminal_title_stripped: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  title: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
  tokens: Schema.optionalKey(
    Schema.Record(
      Schema.String.check(Schema.isPattern(new RegExp("^[A-Za-z0-9_-]{1,32}$"))),
      Schema.String
    ).check(Schema.isMaxProperties(32))
  ),
  workspace_id: Schema.String
})

const HerdrTabInfoSchema = Schema.Struct({
  agent_status: HerdrAgentStatusSchema,
  focused: Schema.Boolean,
  label: Schema.String,
  number: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  pane_count: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  tab_id: Schema.String,
  workspace_id: Schema.String
})

const HerdrWorkspaceWorktreeInfoSchema = Schema.Struct({
  checkout_path: Schema.String,
  is_linked_worktree: Schema.Boolean,
  repo_key: Schema.String,
  repo_name: Schema.String,
  repo_root: Schema.String
})

const HerdrWorkspaceInfoSchema = Schema.Struct({
  active_tab_id: Schema.String,
  agent_status: HerdrAgentStatusSchema,
  focused: Schema.Boolean,
  label: Schema.String,
  number: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  pane_count: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  tab_count: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  tokens: Schema.optionalKey(
    Schema.Record(
      Schema.String.check(Schema.isPattern(new RegExp("^[A-Za-z0-9_-]{1,32}$"))),
      Schema.String
    ).check(Schema.isMaxProperties(32))
  ),
  workspace_id: Schema.String,
  worktree: Schema.optionalKey(Schema.Union([HerdrWorkspaceWorktreeInfoSchema, Schema.Null]))
})

export const HerdrWorkspaceCreatedResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    root_pane: HerdrPaneInfoSchema,
    tab: HerdrTabInfoSchema,
    type: Schema.Literal("workspace_created"),
    workspace: HerdrWorkspaceInfoSchema
  })
})
export const decodeHerdrWorkspaceCreatedResponse = Schema.decodeUnknownOption(
  HerdrWorkspaceCreatedResponseSchema
)

export const HerdrWorkspaceListResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    type: Schema.Literal("workspace_list"),
    workspaces: Schema.Array(HerdrWorkspaceInfoSchema)
  })
})
export const decodeHerdrWorkspaceListResponse = Schema.decodeUnknownOption(
  HerdrWorkspaceListResponseSchema
)

export const HerdrTabCreatedResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    root_pane: HerdrPaneInfoSchema,
    tab: HerdrTabInfoSchema,
    type: Schema.Literal("tab_created")
  })
})
export const decodeHerdrTabCreatedResponse = Schema.decodeUnknownOption(
  HerdrTabCreatedResponseSchema
)

export const HerdrTabListResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    tabs: Schema.Array(HerdrTabInfoSchema),
    type: Schema.Literal("tab_list")
  })
})
export const decodeHerdrTabListResponse = Schema.decodeUnknownOption(HerdrTabListResponseSchema)

export const HerdrAgentInfoResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    agent: HerdrAgentInfoSchema,
    type: Schema.Literal("agent_info")
  })
})
export const decodeHerdrAgentInfoResponse = Schema.decodeUnknownOption(HerdrAgentInfoResponseSchema)

export const HerdrPaneInfoResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    pane: HerdrPaneInfoSchema,
    type: Schema.Literal("pane_info")
  })
})
export const decodeHerdrPaneInfoResponse = Schema.decodeUnknownOption(HerdrPaneInfoResponseSchema)

export const HerdrPaneListResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    panes: Schema.Array(HerdrPaneInfoSchema),
    type: Schema.Literal("pane_list")
  })
})
export const decodeHerdrPaneListResponse = Schema.decodeUnknownOption(HerdrPaneListResponseSchema)

export const HerdrPaneCurrentResponseSchema = Schema.Struct({
  id: Schema.String,
  result: Schema.Struct({
    pane: HerdrPaneInfoSchema,
    type: Schema.Literal("pane_current")
  })
})
export const decodeHerdrPaneCurrentResponse = Schema.decodeUnknownOption(
  HerdrPaneCurrentResponseSchema
)
